<script lang="ts">
	import { base } from '$app/paths';
	import { browser } from '$app/environment';
	import { onMount } from 'svelte';
	import { cfrToUrl } from '$lib/cfr-utils';

	interface Stage {
		id: string;
		name: string;
		shortName: string;
	}

	interface ModelType {
		id: string;
		name: string;
		description: string;
	}

	interface RiskSubdomain {
		id: string;
		code: string;
		name: string;
		shortName: string;
		domain: string;
		description: string;
		cfrReferences: string[];
	}

	interface Concern {
		id: string;
		riskSubdomain: string;
		stages: string[];
		category: string;
		reviewerText: string;
		investigatorText: string;
		canonical: string;
		cfrReferences: string[];
	}

	let stages: Stage[] = $state([]);
	let modelTypes: ModelType[] = $state([]);
	let riskSubdomains: RiskSubdomain[] = $state([]);
	let concernsBySubdomain: Record<string, Concern[]> = $state({});
	let modelTypeRelevance: Record<string, string[]> = $state({});

	let selectedStage: string = $state('');
	let selectedModelTypes: string[] = $state([]);
	let checkedItems: Set<string> = $state(new Set());
	let loading = $state(true);

	onMount(async () => {
		try {
			const [stagesRes, modelsRes, subdomainsRes, concernsRes, schemaRes] = await Promise.all([
				fetch(`${base}/data/stages.json`),
				fetch(`${base}/data/model-types.json`),
				fetch(`${base}/data/risk-subdomains.json`),
				fetch(`${base}/data/review-concerns.json`),
				fetch(`${base}/data/unified-schema.json`)
			]);

			const stagesData = await stagesRes.json();
			const modelsData = await modelsRes.json();
			const subdomainsData = await subdomainsRes.json();
			const concernsData = await concernsRes.json();
			const schemaData = await schemaRes.json();

			stages = stagesData.stages;
			modelTypes = modelsData.modelTypes;
			riskSubdomains = subdomainsData.riskSubdomains;

			// Group concerns by riskSubdomain
			const grouped: Record<string, Concern[]> = {};
			for (const concern of concernsData.concerns) {
				if (!grouped[concern.riskSubdomain]) {
					grouped[concern.riskSubdomain] = [];
				}
				grouped[concern.riskSubdomain].push(concern);
			}
			concernsBySubdomain = grouped;

			modelTypeRelevance = schemaData.modelTypeToSubdomainRelevance || {};
		} catch (e) {
			console.error('Failed to load data:', e);
		} finally {
			loading = false;
		}
	});

	function toggleModelType(id: string) {
		if (selectedModelTypes.includes(id)) {
			selectedModelTypes = selectedModelTypes.filter(m => m !== id);
		} else {
			selectedModelTypes = [...selectedModelTypes, id];
		}
	}

	function getRelevantSubdomains(): RiskSubdomain[] {
		if (selectedModelTypes.length === 0) {
			return riskSubdomains;
		}
		const relevantIds = new Set<string>();
		for (const modelType of selectedModelTypes) {
			const ids = modelTypeRelevance[modelType] || [];
			ids.forEach(id => relevantIds.add(id));
		}
		return riskSubdomains.filter(s => relevantIds.has(s.id));
	}

	function getConcernsForSubdomain(subdomainId: string): Concern[] {
		const concerns = concernsBySubdomain[subdomainId];
		if (!concerns) return [];
		if (!selectedStage) return concerns;
		return concerns.filter(c => c.stages.includes(selectedStage));
	}

	function toggleCheck(id: string) {
		const newSet = new Set(checkedItems);
		if (newSet.has(id)) {
			newSet.delete(id);
		} else {
			newSet.add(id);
		}
		checkedItems = newSet;
	}

	function getProgress(): { checked: number; total: number } {
		let total = 0;
		const relevantSubdomains = getRelevantSubdomains();
		for (const subdomain of relevantSubdomains) {
			const concerns = getConcernsForSubdomain(subdomain.id);
			total += concerns.length;
		}
		return { checked: checkedItems.size, total };
	}

	$effect(() => {
		// Reset checked items when filters change
		checkedItems = new Set();
	});

	function getSelectedStageName(): string {
		if (!selectedStage) return 'All Stages';
		const stage = stages.find(s => s.id === selectedStage);
		return stage ? stage.shortName : 'All Stages';
	}

	function resetChecklist() {
		checkedItems = new Set();
		selectedStage = '';
		selectedModelTypes = [];
	}

	async function exportDocx() {
		if (!browser) return;

		const { Document, Paragraph, TextRun, HeadingLevel, Packer, Table, TableRow, TableCell, BorderStyle, WidthType } = await import('docx');
		const { saveAs } = await import('file-saver');

		const children: any[] = [];
		const progress = getProgress();
		const stageName = getSelectedStageName();
		const modelNames = selectedModelTypes.length > 0
			? selectedModelTypes.map(id => modelTypes.find(m => m.id === id)?.name).filter(Boolean).join(', ')
			: 'All';

		children.push(
			new Paragraph({
				text: 'IRB AI Reviewer Checklist',
				heading: HeadingLevel.TITLE,
				spacing: { after: 100 }
			}),
			new Paragraph({
				children: [
					new TextRun({ text: 'Generated by AI Oversight Tools', italics: true, size: 24, color: '666666' })
				],
				spacing: { after: 400 }
			})
		);

		children.push(
			new Table({
				width: { size: 100, type: WidthType.PERCENTAGE },
				borders: {
					top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
					bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
					left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
					right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
					insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
					insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }
				},
				rows: [
					new TableRow({
						children: [
							new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Development Stage', bold: true })] })] }),
							new TableCell({ children: [new Paragraph(stageName)] })
						]
					}),
					new TableRow({
						children: [
							new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Model Types', bold: true })] })] }),
							new TableCell({ children: [new Paragraph(modelNames)] })
						]
					}),
					new TableRow({
						children: [
							new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Date Generated', bold: true })] })] }),
							new TableCell({ children: [new Paragraph(new Date().toLocaleDateString())] })
						]
					})
				]
			}),
			new Paragraph({ spacing: { after: 400 } })
		);

		const relevantSubdomains = getRelevantSubdomains();
		for (const subdomain of relevantSubdomains) {
			const concerns = getConcernsForSubdomain(subdomain.id);
			if (concerns.length === 0) continue;

			children.push(
				new Paragraph({
					children: [
						new TextRun({ text: `[${subdomain.code}] `, bold: true, color: '3B82F6' }),
						new TextRun({ text: subdomain.shortName, bold: true })
					],
					heading: HeadingLevel.HEADING_2,
					spacing: { before: 300, after: 100 }
				})
			);

			if (subdomain.cfrReferences.length > 0) {
				children.push(
					new Paragraph({
						children: [
							new TextRun({ text: 'CFR: ', bold: true, size: 20, color: '666666' }),
							new TextRun({ text: subdomain.cfrReferences.join(', '), size: 20, color: '666666' })
						],
						spacing: { after: 150 }
					})
				);
			}

			for (const concern of concerns) {
				const isChecked = checkedItems.has(concern.id);
				const checkbox = isChecked ? '\u2611' : '\u2610';
				const stageTags = concern.stages.map(s => s.replace('stage-', 'S')).join(' ');

				children.push(
					new Paragraph({
						children: [
							new TextRun({ text: `${checkbox} `, font: 'Segoe UI Symbol', size: 24 }),
							new TextRun({ text: concern.reviewerText, size: 22 }),
							new TextRun({ text: `  [${stageTags}]`, size: 18, color: '888888' })
						],
						spacing: { after: 80 },
						indent: { left: 360 }
					})
				);
			}
		}

		children.push(
			new Paragraph({ spacing: { before: 400 } }),
			new Paragraph({
				children: [
					new TextRun({ text: 'Progress Summary', bold: true, size: 28 })
				],
				heading: HeadingLevel.HEADING_2,
				spacing: { after: 100 }
			}),
			new Paragraph({
				children: [
					new TextRun({ text: `${progress.checked} of ${progress.total} items reviewed`, size: 24 }),
					new TextRun({ text: ` (${progress.total > 0 ? Math.round((progress.checked / progress.total) * 100) : 0}%)`, size: 24, color: '666666' })
				]
			})
		);

		const doc = new Document({
			sections: [{
				properties: {},
				children
			}]
		});

		const blob = await Packer.toBlob(doc);
		saveAs(blob, `IRB-Reviewer-Checklist-${stageName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.docx`);
	}
</script>

<svelte:head>
	<title>Reviewer Checklist - AI Oversight Tools</title>
</svelte:head>

<div class="page-header">
	<h1>IRB Reviewer Checklist</h1>
	<p>Select the development stage and AI model type(s) to see applicable review prompts</p>
</div>

<div class="info-box">
	<p>This checklist maps AI-specific risk review prompts to federal regulatory approval criteria
	(45 CFR 46 and 21 CFR 56). Each prompt is tagged with the applicable stage(s) and linked
	to the CFR sections that require this consideration during IRB review.</p>
	<p class="disclaimer"><strong>Note:</strong> This checklist is intended for use after a project has been determined to be
	subject to IRB review under 21 CFR 56. HSR determinations and FDA device determinations
	are performed separately. For guidance on those determinations, see the
	<a href="https://www.techinhsr.com" target="_blank" rel="noopener">AIHSR Decision Tree at TechInHSR.com</a>.</p>
</div>

{#if loading}
	<div class="loading">Loading checklist data...</div>
{:else}
	<div class="filters">
		<div class="filter-group">
			<label for="stage-select">Development Stage</label>
			<select id="stage-select" bind:value={selectedStage}>
				<option value="">All Stages</option>
				{#each stages as stage}
					<option value={stage.id}>{stage.shortName}</option>
				{/each}
			</select>
		</div>

		<div class="filter-group">
			<span id="model-type-label" class="filter-label">AI Model Type(s)</span>
			<div class="model-chips" role="group" aria-labelledby="model-type-label">
				{#each modelTypes.slice(0, 8) as model}
					<button
						class="chip"
						class:selected={selectedModelTypes.includes(model.id)}
						onclick={() => toggleModelType(model.id)}
						aria-pressed={selectedModelTypes.includes(model.id)}
					>
						{model.name}
					</button>
				{/each}
			</div>
		</div>
	</div>

	<!-- Progress bar -->
	{@const progress = getProgress()}
	<div class="progress-bar">
		<div class="progress-text">
			<span>Progress: {progress.checked} / {progress.total} items reviewed</span>
			<span>{progress.total > 0 ? Math.round((progress.checked / progress.total) * 100) : 0}%</span>
		</div>
		<div class="progress-track">
			<div class="progress-fill" style="width: {progress.total > 0 ? (progress.checked / progress.total) * 100 : 0}%"></div>
		</div>
		<button class="download-btn" onclick={() => exportDocx()} disabled={progress.total === 0}>
			Download Checklist (.docx)
		</button>
	</div>

	<!-- Completion panel -->
	{#if progress.checked === progress.total && progress.total > 0}
		<div class="completion-panel">
			<div class="completion-icon">&#10003;</div>
			<h2 class="completion-title">Review Complete</h2>
			<p class="completion-summary">All {progress.total} items reviewed for {getSelectedStageName()}</p>
			<div class="completion-actions">
				<button class="completion-btn disabled" disabled title="Coming soon">
					Download this checklist
				</button>
				<a href="{base}/protocol-builder" class="completion-btn primary">
					Continue to Protocol Builder
				</a>
				<button class="completion-btn secondary" onclick={() => resetChecklist()}>
					Review again with different filters
				</button>
			</div>
		</div>
	{/if}

	<!-- Checklist -->
	<div class="checklist">
		{#each getRelevantSubdomains() as subdomain}
			{@const concerns = getConcernsForSubdomain(subdomain.id)}
			{#if concerns.length > 0}
				<div class="subdomain-section">
					<div class="subdomain-header">
						<div class="subdomain-title">
							<span class="code">{subdomain.code}</span>
							<h2>{subdomain.shortName}</h2>
						</div>
						{#if subdomain.cfrReferences.length > 0}
							<div class="cfr-refs">
								{#each subdomain.cfrReferences.slice(0, 2) as ref}
									{@const url = cfrToUrl(ref)}
									{#if url}
										<a class="cfr-badge cfr-link" href={url} target="_blank" rel="noopener">{ref}</a>
									{:else}
										<span class="cfr-badge">{ref}</span>
									{/if}
								{/each}
							</div>
						{/if}
					</div>

					<div class="prompts">
						{#each concerns as concern}
							<label class="prompt-item" class:checked={checkedItems.has(concern.id)}>
								<input
									type="checkbox"
									checked={checkedItems.has(concern.id)}
									onchange={() => toggleCheck(concern.id)}
								/>
								<span class="prompt-text">{concern.reviewerText}</span>
								<span class="stage-tags">
									{#each concern.stages as stg}
										<span class="stage-tag">{stg.replace('stage-', 'S')}</span>
									{/each}
								</span>
							</label>
						{/each}
					</div>
				</div>
			{/if}
		{/each}
	</div>
{/if}

<style>
	.page-header {
		margin-bottom: 2rem;
	}

	.page-header h1 {
		font-size: 1.75rem;
		color: #f1f5f9;
		margin-bottom: 0.5rem;
	}

	.page-header p {
		color: #94a3b8;
	}

	.info-box {
		background: rgba(96, 165, 250, 0.08);
		border: 1px solid rgba(96, 165, 250, 0.2);
		border-radius: 8px;
		padding: 1rem 1.25rem;
		margin: 0 0 1.5rem 0;
		font-size: 0.85rem;
		line-height: 1.6;
		color: #cbd5e1;
	}

	.info-box p + p {
		margin-top: 0.5rem;
	}

	.info-box .disclaimer {
		font-size: 0.8rem;
		color: #94a3b8;
	}

	.info-box a {
		color: #60a5fa;
		text-decoration: none;
	}

	.info-box a:hover {
		text-decoration: underline;
	}

	.loading {
		text-align: center;
		color: #94a3b8;
		padding: 3rem;
	}

	.filters {
		background: #1e293b;
		border: 1px solid #334155;
		border-radius: 0.75rem;
		padding: 1.5rem;
		margin-bottom: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.filter-group label,
	.filter-group .filter-label {
		display: block;
		font-size: 0.875rem;
		font-weight: 600;
		color: #94a3b8;
		margin-bottom: 0.5rem;
	}

	select {
		background: #0f172a;
		border: 1px solid #334155;
		border-radius: 0.375rem;
		padding: 0.5rem 1rem;
		color: #e2e8f0;
		font-size: 0.875rem;
		width: 100%;
		max-width: 300px;
	}

	.model-chips {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
	}

	.chip {
		background: #0f172a;
		border: 1px solid #334155;
		border-radius: 1rem;
		padding: 0.375rem 0.875rem;
		color: #94a3b8;
		font-size: 0.8125rem;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.chip:hover {
		border-color: #60a5fa;
		color: #e2e8f0;
	}

	.chip.selected {
		background: #1e40af;
		border-color: #60a5fa;
		color: #f1f5f9;
	}

	.progress-bar {
		background: #1e293b;
		border: 1px solid #334155;
		border-radius: 0.5rem;
		padding: 1rem;
		margin-bottom: 1.5rem;
	}

	.progress-text {
		display: flex;
		justify-content: space-between;
		font-size: 0.875rem;
		color: #94a3b8;
		margin-bottom: 0.5rem;
	}

	.progress-track {
		height: 8px;
		background: #0f172a;
		border-radius: 4px;
		overflow: hidden;
	}

	.progress-fill {
		height: 100%;
		background: #22c55e;
		border-radius: 4px;
		transition: width 0.3s ease;
	}

	.checklist {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.subdomain-section {
		background: #1e293b;
		border: 1px solid #334155;
		border-radius: 0.75rem;
		overflow: hidden;
	}

	.subdomain-header {
		background: #0f172a;
		padding: 1rem 1.5rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
		flex-wrap: wrap;
		gap: 0.75rem;
	}

	.subdomain-title {
		display: flex;
		align-items: center;
		gap: 0.75rem;
	}

	.code {
		background: #60a5fa;
		color: #0f172a;
		padding: 0.25rem 0.5rem;
		border-radius: 0.25rem;
		font-size: 0.75rem;
		font-weight: 700;
	}

	.subdomain-header h2 {
		font-size: 1rem;
		color: #f1f5f9;
	}

	.cfr-refs {
		display: flex;
		gap: 0.375rem;
	}

	.cfr-badge {
		background: #334155;
		color: #94a3b8;
		padding: 0.25rem 0.5rem;
		border-radius: 0.25rem;
		font-size: 0.6875rem;
	}

	.cfr-link {
		text-decoration: none;
		color: #94a3b8;
		transition: color 0.15s ease;
	}

	.cfr-link:hover {
		color: #60a5fa;
		text-decoration: underline;
	}

	.prompts {
		padding: 0.5rem;
	}

	.prompt-item {
		display: flex;
		align-items: flex-start;
		gap: 0.75rem;
		padding: 0.75rem 1rem;
		border-radius: 0.5rem;
		cursor: pointer;
		transition: background 0.15s ease;
	}

	.prompt-item:hover {
		background: #0f172a;
	}

	.prompt-item.checked {
		opacity: 0.6;
	}

	.prompt-item input[type="checkbox"] {
		width: 18px;
		height: 18px;
		margin-top: 0.125rem;
		flex-shrink: 0;
		accent-color: #22c55e;
	}

	.prompt-text {
		flex: 1;
		color: #e2e8f0;
		font-size: 0.875rem;
		line-height: 1.5;
	}

	.stage-tags {
		display: flex;
		gap: 0.25rem;
		flex-shrink: 0;
	}

	.stage-tag {
		background: #334155;
		color: #94a3b8;
		padding: 0.125rem 0.375rem;
		border-radius: 0.25rem;
		font-size: 0.625rem;
		font-weight: 600;
	}

	.completion-panel {
		background: rgba(34, 197, 94, 0.08);
		border: 2px solid rgba(34, 197, 94, 0.4);
		border-radius: 0.75rem;
		padding: 2rem;
		margin-bottom: 1.5rem;
		text-align: center;
	}

	.completion-icon {
		font-size: 2.5rem;
		color: #22c55e;
		margin-bottom: 0.5rem;
	}

	.completion-title {
		font-size: 1.5rem;
		color: #22c55e;
		margin-bottom: 0.5rem;
	}

	.completion-summary {
		color: #94a3b8;
		font-size: 0.95rem;
		margin-bottom: 1.5rem;
	}

	.completion-actions {
		display: flex;
		gap: 0.75rem;
		justify-content: center;
		flex-wrap: wrap;
	}

	.completion-btn {
		padding: 0.625rem 1.25rem;
		border-radius: 0.5rem;
		font-size: 0.875rem;
		font-weight: 600;
		cursor: pointer;
		border: 1px solid #334155;
		background: #1e293b;
		color: #e2e8f0;
		text-decoration: none;
		transition: all 0.15s ease;
	}

	.completion-btn:hover:not(:disabled) {
		border-color: #60a5fa;
	}

	.completion-btn.primary {
		background: #22c55e;
		border-color: #22c55e;
		color: #0f172a;
	}

	.completion-btn.primary:hover {
		background: #16a34a;
		border-color: #16a34a;
	}

	.completion-btn.secondary {
		background: transparent;
		border-color: #475569;
		color: #94a3b8;
	}

	.completion-btn.secondary:hover {
		border-color: #60a5fa;
		color: #e2e8f0;
	}

	.completion-btn.disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Focus states for accessibility */
	select:focus-visible {
		outline: var(--focus-ring-width, 2px) solid var(--focus-ring-color, #60a5fa);
		outline-offset: var(--focus-ring-offset, 2px);
	}

	.chip:focus-visible {
		outline: var(--focus-ring-width, 2px) solid var(--focus-ring-color, #60a5fa);
		outline-offset: var(--focus-ring-offset, 2px);
	}

	.prompt-item input[type="checkbox"]:focus-visible {
		outline: var(--focus-ring-width, 2px) solid var(--focus-ring-color, #60a5fa);
		outline-offset: var(--focus-ring-offset, 2px);
	}
</style>
